/**
 * Created with JetBrains WebStorm.
 * User: ty
 * Date: 13-9-5
 * Time: 上午9:22
 * To change this template use File | Settings | File Templates.
 */
var DE=DE||{};
DE.config={
    root:"/design",
    maxMediaSize:"200m",
    maxImageSize:"2m",
    userStatus:{
        enabled:"enabled",
        disabled:"disabled"
    },
    scrollScreenType:{
        hotUser:"hotUser",
        project:"project",
        resource:"resource",
        userEntity:"userEntity"
    },
    errorCode:{
        timeout:"登陆超时，请重新登陆！"
    },
    ajaxUrls:{
        uploadFileUrl:"http://192.168.2.112/upload?test=1",
        uploadAction:"#",
        getProjectDetail:"#",
        getProjectsByTag:"#",
        getAllProjects:"/design/data/projects.json",
        getAllResource:"/design/data/resource.json",
        getEntityMedias:"/design/data/medias.json",
        deleteEntity:"#",
        hideEntity:"#",
        getEntityAttachments:"/design/data/attachments.json",
        getEntityDetail:"/design/data/entityDetail.json",
        getProjectsBySearch:"#",
        getTags:"/design/data/tags.json",
        addPraise:"#",
        deletePraise:"#",
        addHonor:"#",
        deleteHonor:"#",
        getSimilarEntities:"/design/data/similarEntities.json",
        getComments:"/design/data/comments.json",
        postComment:"#",
        deleteComment:"#",
        getHotUsers:"/design/data/hotUsers.json",
        getUserById:"/design/data/user.json",
        getUserEntities:"/design/data/userEntities.json",
        login:"http://192.168.2.112/design/login",
        checkLogin:"http://192.168.2.112/design/login",
        sendOpenId:"http://192.168.2.112/design/login",
        bandOldCount:"#",
        getValidCode:"http://lotusprize.com/design/captcha.jpg",
        register:"http://lotusprize.com/design/register",
        changeProfile:"/design",
        changePassword:"/design",
        forgetPassword:"#",
        uploadFigure:"/design",
        emailValidate:"http://lotusprize.com/design/account-email-unique",
        usernameValidate:"http://lotusprize.com/design/account-fullname-unique"
    },
    entityTypes:{
        project:"project",
        resource:"resource"
    },
    urls:{
        indexWork:"project/all",
        indexResource:"resource/all",
        entityDetail:"entity/entityId",
        tagWorks:"tag/tagName",
        hotUsers:"user/hot",
        userDetail:"user/userId",
        search:"search/searchContent",
        uploadWork:"upload/entity",
        editWork:"edit/entityId"
    },
    linkTypes:{
        user:"user",
        project:"project",
        resource:"resource",
        upload:"upload"
    },
    roles:{
        admin:"admin",
        user:"user",
        vip:"VIP"
    }

};
Object.freeze(DE.config);